services:
  postgres:
    restart: 'no'

  redis:
    restart: 'no'

  mailpit:
    restart: 'no'

  api:
    restart: 'no'

  worker:
    restart: 'no'
    ports:
      - '${BIND_ADDRESS:-127.0.0.1}:${WORKER_HEALTH_PORT:-4100}:${WORKER_HEALTH_PORT:-4100}'

  web:
    restart: 'no'
