import { randomBytes } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { FRIGATE_STRIKE_RESOLVER_VERSION, GALAXY_COORDINATE_BOUNDS, planFrigateStrike } from '@eonrover/shared';
import { prisma } from '../lib/prisma';
import { getUniverseConfig } from './gameConfig';
import { syncLockedPlanetResources } from './planetService';
import { scheduleFrigateStrikeArrivalWakeup } from './frigateStrikeArrivalSchedulingService';

const ATTEMPTS = 3;
export type FrigateStrikeLaunchErrorCode = 'ORIGIN_NOT_OWNED' | 'INVALID_TARGET' | 'TARGET_UNAVAILABLE' | 'TARGET_PROTECTED' | 'INSUFFICIENT_FRIGATES' | 'INSUFFICIENT_HELIOX' | 'STRIKE_IN_PROGRESS' | 'STRIKE_UNAVAILABLE';
export class FrigateStrikeLaunchError extends Error { constructor(readonly code: FrigateStrikeLaunchErrorCode, message: string) { super(message); this.name = 'FrigateStrikeLaunchError'; } }
export type FrigateStrikeLaunchInput = { userId: string; originPlanetId: string; target: unknown; quantity: unknown };
export type AcceptedFrigateStrikeLaunch = { missionId: string; originPlanetId: string; target: { galaxy: number; system: number; slot: number }; ships: { frigate: number }; outboundFuelHeliox: number; returnFuelHeliox: number; outboundDurationSeconds: number; returnDurationSeconds: number; departedAt: Date; arrivesAt: Date; returnsAt: Date; phase: 'OUTBOUND' };
const fail = (code: FrigateStrikeLaunchErrorCode, message: string): never => { throw new FrigateStrikeLaunchError(code, message); };
const retryable = (error: unknown) => error instanceof Prisma.PrismaClientKnownRequestError && (error.code === 'P2034' || (error.code === 'P2010' && error.meta?.code === '40001'));
function target(value: unknown) { if (!value || typeof value !== 'object' || Array.isArray(value)) return fail('INVALID_TARGET', 'The strike target is invalid.'); const values = value as Record<string, unknown>; if (Object.keys(values).sort().join(',') !== 'galaxy,slot,system' || !['galaxy', 'system', 'slot'].every((key) => typeof values[key] === 'number' && Number.isSafeInteger(values[key])) || (values.galaxy as number) < GALAXY_COORDINATE_BOUNDS.galaxy.min || (values.galaxy as number) > GALAXY_COORDINATE_BOUNDS.galaxy.max || (values.system as number) < GALAXY_COORDINATE_BOUNDS.system.min || (values.system as number) > GALAXY_COORDINATE_BOUNDS.system.max || (values.slot as number) < GALAXY_COORDINATE_BOUNDS.slot.min || (values.slot as number) > GALAXY_COORDINATE_BOUNDS.slot.max) return fail('INVALID_TARGET', 'The strike target is invalid.'); return values as { galaxy: number; system: number; slot: number }; }
function tech(rows: Array<{ key: string; level: number }>) { const levels = new Map(rows.map((row) => [row.key, row.level])); return { weaponTech: levels.get('weaponTech') ?? 0, shieldTech: levels.get('shieldTech') ?? 0, armourTech: levels.get('armourTech') ?? 0 }; }
/** Internal only: PostgreSQL reservation commits before best-effort Redis wake-up. */
export async function launchCanonicalFrigateStrike(input: FrigateStrikeLaunchInput): Promise<AcceptedFrigateStrikeLaunch> {
  if (!input || typeof input.userId !== 'string' || !input.userId || typeof input.originPlanetId !== 'string' || !input.originPlanetId || Object.keys(input).some((key) => !['userId', 'originPlanetId', 'target', 'quantity'].includes(key))) fail('INVALID_TARGET', 'The strike command is invalid.');
  const coordinates = target(input.target); const config = await getUniverseConfig();
  for (let attempt = 0; attempt < ATTEMPTS; attempt += 1) try {
    const accepted = await prisma.$transaction(async (tx) => {
      const candidate = await tx.planet.findUnique({ where: { galaxy_system_slot: coordinates }, select: { id: true, ownerId: true } });
      if (!candidate) throw new FrigateStrikeLaunchError('TARGET_UNAVAILABLE', 'The strike target is unavailable.');
      for (const id of [...new Set([input.userId, candidate.ownerId])].sort()) await tx.$queryRaw`SELECT "id" FROM "User" WHERE "id"=${id} FOR UPDATE`;
      const attacker = await tx.user.findUnique({ where: { id: input.userId }, select: { id: true, status: true, emailVerifiedAt: true } });
      if (!attacker || attacker.status !== 'ACTIVE' || !attacker.emailVerifiedAt) throw new FrigateStrikeLaunchError('ORIGIN_NOT_OWNED', 'The origin planet is not available to this account.');
      await tx.$queryRaw`SELECT "id" FROM "Planet" WHERE "id"=${input.originPlanetId} FOR UPDATE`; const origin = await tx.planet.findUnique({ where: { id: input.originPlanetId } });
      if (!origin || origin.ownerId !== attacker.id) throw new FrigateStrikeLaunchError('ORIGIN_NOT_OWNED', 'The origin planet is not available to this account.');
      await tx.$queryRaw`SELECT "id" FROM "Planet" WHERE "id"=${candidate.id} FOR UPDATE`; const destination = await tx.planet.findUnique({ where: { id: candidate.id }, include: { owner: { select: { id: true, status: true, emailVerifiedAt: true, protectedUntil: true } } } }); const departedAt = new Date();
      if (!destination || destination.ownerId === attacker.id || destination.galaxy !== coordinates.galaxy || destination.system !== coordinates.system || destination.slot !== coordinates.slot || destination.owner.status !== 'ACTIVE' || !destination.owner.emailVerifiedAt) throw new FrigateStrikeLaunchError('TARGET_UNAVAILABLE', 'The strike target is unavailable.'); if (destination.owner.protectedUntil && destination.owner.protectedUntil > departedAt) throw new FrigateStrikeLaunchError('TARGET_PROTECTED', 'The strike target is protected.');
      let plan: ReturnType<typeof planFrigateStrike>; try { plan = planFrigateStrike({ origin: { galaxy: origin.galaxy, system: origin.system, slot: origin.slot }, target: coordinates, quantity: input.quantity, fleetSpeed: config.fleetSpeed }); } catch { throw new FrigateStrikeLaunchError('INVALID_TARGET', 'The strike target or Frigate quantity is invalid.'); }
      const synced = await syncLockedPlanetResources(tx, origin, departedAt, config.economySpeed); await tx.$queryRaw`SELECT "id" FROM "Ship" WHERE "planetId"=${origin.id} AND "key"='frigate' FOR UPDATE`; const frigates = await tx.ship.findUnique({ where: { planetId_key: { planetId: origin.id, key: 'frigate' } }, select: { count: true } });
      await tx.$queryRaw`SELECT "id" FROM "FleetMission" WHERE "missionType"='ATTACK' AND "frigateStrikeOriginPlanetId"=${origin.id} AND "frigateStrikeTargetPlanetId" IS NOT NULL AND "frigateStrikeAttackerId" IS NOT NULL AND "frigateStrikeDefenderId" IS NOT NULL AND "frigateStrikePhase" IN ('OUTBOUND','RETURNING') FOR UPDATE`;
      if (await tx.fleetMission.findFirst({ where: { missionType: 'ATTACK', frigateStrikeOriginPlanetId: origin.id, frigateStrikePhase: { in: ['OUTBOUND', 'RETURNING'] } }, select: { id: true } })) fail('STRIKE_IN_PROGRESS', 'A Frigate strike is already active from this planet.');
      if (!frigates || frigates.count < plan.ships.frigate) fail('INSUFFICIENT_FRIGATES', 'The origin planet does not have enough Frigates.'); const fuel = plan.outboundFuelHeliox + plan.returnFuelHeliox; if (synced.planet.heliox < fuel) fail('INSUFFICIENT_HELIOX', 'The origin planet does not have enough Heliox.');
      if ((await tx.ship.updateMany({ where: { planetId: origin.id, key: 'frigate', count: { gte: plan.ships.frigate } }, data: { count: { decrement: plan.ships.frigate } } })).count !== 1) fail('INSUFFICIENT_FRIGATES', 'The origin planet does not have enough Frigates.'); await tx.planet.update({ where: { id: origin.id }, data: { heliox: synced.planet.heliox - fuel } });
      const arrivesAt = new Date(departedAt.getTime() + plan.outboundDurationSeconds * 1000); const returnsAt = new Date(arrivesAt.getTime() + plan.returnDurationSeconds * 1000); const mission = await tx.fleetMission.create({ data: { originId: origin.id, targetId: destination.id, targetGalaxy: destination.galaxy, targetSystem: destination.system, targetSlot: destination.slot, missionType: 'ATTACK', ships: plan.ships, cargo: { alloy: 0, heliox: 0, aether: 0 }, speedPercent: 100, departedAt, arrivesAt, returnsAt, status: 'OUTBOUND', frigateStrikeOriginPlanetId: origin.id, frigateStrikeTargetPlanetId: destination.id, frigateStrikeAttackerId: attacker.id, frigateStrikeDefenderId: destination.ownerId, frigateStrikeShips: plan.ships, frigateStrikeOutboundFuelHeliox: plan.outboundFuelHeliox, frigateStrikeReturnFuelHeliox: plan.returnFuelHeliox, frigateStrikeOutboundDurationSeconds: plan.outboundDurationSeconds, frigateStrikeReturnDurationSeconds: plan.returnDurationSeconds, frigateStrikeResolverVersion: FRIGATE_STRIKE_RESOLVER_VERSION, frigateStrikeResolverSeed: randomBytes(32).toString('hex'), frigateStrikeAttackerTechnology: tech(await tx.research.findMany({ where: { userId: attacker.id, key: { in: ['weaponTech', 'shieldTech', 'armourTech'] } }, select: { key: true, level: true } })), frigateStrikePhase: 'OUTBOUND' } });
      return { missionId: mission.id, originPlanetId: origin.id, target: coordinates, ships: plan.ships, outboundFuelHeliox: plan.outboundFuelHeliox, returnFuelHeliox: plan.returnFuelHeliox, outboundDurationSeconds: plan.outboundDurationSeconds, returnDurationSeconds: plan.returnDurationSeconds, departedAt, arrivesAt, returnsAt, phase: 'OUTBOUND' as const };
    }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
    await scheduleFrigateStrikeArrivalWakeup(accepted.missionId); return accepted;
  } catch (error) { if (error instanceof FrigateStrikeLaunchError) throw error; if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') throw new FrigateStrikeLaunchError('STRIKE_IN_PROGRESS', 'A Frigate strike is already active from this planet.'); if (retryable(error) && attempt + 1 < ATTEMPTS) continue; if (retryable(error)) throw new FrigateStrikeLaunchError('STRIKE_UNAVAILABLE', 'Strike launch could not be completed. Please try again.'); throw error; }
  throw new FrigateStrikeLaunchError('STRIKE_UNAVAILABLE', 'Strike launch could not be completed. Please try again.');
}
