'use client';

import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import StatusPanel from '@/components/StatusPanel';
import { apiDelete, apiGet, apiPost } from '@/lib/api';
import { enumLabel, formatDateTime, formatNumber, formatRelativeCountdown } from '@/lib/formatters';
import { getErrorMessage, useApiData } from '@/lib/useApiData';
import { ShipyardReadOnlyResponse } from '@/lib/web-types';

export default function ShipyardPage() {
  const { planetId } = useParams<{ planetId: string }>();
  const load = useCallback(() => apiGet<ShipyardReadOnlyResponse>(`/api/planets/${encodeURIComponent(planetId)}/shipyard`), [planetId]);
  const { data, loading, error, reload } = useApiData(load);
  const [quantities, setQuantities] = useState<Record<string, number>>({});
  const [busy, setBusy] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [confirmingCancellation, setConfirmingCancellation] = useState(false);
  const [now, setNow] = useState(Date.now());
  const active = data?.activeQueue ?? null;
  useEffect(() => { const interval = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(interval); }, []);
  useEffect(() => { if (active && new Date(active.completesAt).getTime() <= now) void reload(); }, [active, now, reload]);
  function setQuantity(key: string, value: number) { setQuantities((current) => ({ ...current, [key]: Math.max(1, Math.min(100, Number.isFinite(value) ? Math.floor(value) : 1)) })); }
  async function start(key: string) { setBusy(key); setActionError(null); try { await apiPost(`/api/planets/${encodeURIComponent(planetId)}/shipyard`, { key, quantity: quantities[key] ?? 1 }); await reload(); } catch (failure) { setActionError(getErrorMessage(failure)); } finally { setBusy(null); } }
  async function cancel() { if (!active) return; setBusy('cancel'); setActionError(null); try { await apiDelete(`/api/planets/${encodeURIComponent(planetId)}/shipyard/${encodeURIComponent(active.id)}`); setConfirmingCancellation(false); await reload(); } catch (failure) { setActionError(getErrorMessage(failure)); } finally { setBusy(null); } }
  return <section className="stack">
    <div className="panel stack"><h1 style={{ margin: 0 }}>Shipyard</h1><p style={{ margin: 0, color: 'var(--color-text-muted)' }}>Start one authoritative ship batch per planet. Prices, timing and refunds are confirmed by the server.</p></div>
    {loading ? <StatusPanel message="Loading authoritative Shipyard catalogue..." /> : null}
    {error ? <StatusPanel tone="error" title="Unable to load Shipyard" message={error} /> : null}
    {actionError ? <StatusPanel tone="error" title="Shipyard request failed" message={actionError} /> : null}
    {!loading && !error && !data ? <StatusPanel message="No Shipyard data returned." /> : null}
    {data ? <>
      <div className="panel stack"><h2 style={{ margin: 0 }}>Selected Shipyard</h2><p style={{ margin: 0 }}><strong>{data.selectedPlanet.name}</strong> · Shipyard level {data.selectedPlanet.shipyardLevel}</p><p style={{ margin: 0 }}>Resources: {formatNumber(data.selectedPlanet.resources.alloy)} Alloy · {formatNumber(data.selectedPlanet.resources.heliox)} Heliox · {formatNumber(data.selectedPlanet.resources.aether)} Aether</p></div>
      {active ? <div className="panel stack" role="status"><h2 style={{ margin: 0 }}>Construction in progress</h2><p style={{ margin: 0 }}><strong>{active.shipName} × {formatNumber(active.quantity)}</strong></p><p style={{ margin: 0 }}>{formatRelativeCountdown(active.completesAt, now)} remaining · completes {formatDateTime(active.completesAt)}</p><p style={{ margin: 0 }}>Cancellation refund ({active.cancellation.refundPercentage}%): {formatNumber(active.cancellation.refund.alloy)} Alloy · {formatNumber(active.cancellation.refund.heliox)} Heliox · {formatNumber(active.cancellation.refund.aether)} Aether</p>{confirmingCancellation ? <div className="stack" role="alert"><p style={{ margin: 0 }}>Cancelling is irreversible. The displayed persisted refund will be returned to this planet.</p><div><button type="button" onClick={cancel} disabled={busy !== null}>{busy === 'cancel' ? 'Cancelling…' : 'Confirm cancellation'}</button><button type="button" onClick={() => setConfirmingCancellation(false)} disabled={busy !== null}>Keep construction</button></div></div> : <button type="button" onClick={() => setConfirmingCancellation(true)} disabled={busy !== null}>Cancel construction</button>}</div> : null}
      {data.legacyQueue.length ? <div className="panel stack"><h2 style={{ margin: 0 }}>Legacy queue</h2><p style={{ margin: 0, color: 'var(--color-text-muted)' }}>Read-only legacy rows; this page does not alter them.</p>{data.legacyQueue.map((item) => <p key={item.id} style={{ margin: 0 }}>{enumLabel(item.itemKey)} × {formatNumber(item.quantity)} · {item.remaining} remaining · {item.status}</p>)}</div> : null}
      <nav aria-label="Shipyard categories" className="research-category-nav"><ul>{data.categories.map((category) => <li key={category.id}><a href={`#shipyard-${category.id}`}>{category.name}</a></li>)}<li><a href="#shipyard-defences">Defences</a></li></ul></nav>
      <section className="stack" id="shipyard-defences"><h2>Defences</h2><p style={{ margin: 0, color: 'var(--color-text-muted)' }}>Defences protect this planet. Combat outcomes remain server-authoritative.</p><div className="grid research-catalogue-grid">{data.defences.map((defence) => { const quantity = quantities[defence.id] ?? 1; const actionable = defence.availability === 'ACTIVE' && defence.meetsRequirements && defence.affordable && !active; return <article className="panel stack" key={defence.id}><div className="research-card-heading"><h3>{defence.name}</h3><span className="tag">Owned {formatNumber(defence.owned)}</span></div><p style={{ margin: 0 }}>{defence.availabilityReason}</p><dl className="research-details"><div><dt>Cost</dt><dd>{formatNumber(defence.cost.alloy)} Alloy · {formatNumber(defence.cost.heliox)} Heliox · {formatNumber(defence.cost.aether)} Aether</dd></div><div><dt>Estimated duration</dt><dd>{Math.max(1, Math.round(defence.durationSeconds / 60))} minutes</dd></div><div><dt>Statistics</dt><dd>Attack {defence.statistics.attack} · Shield {defence.statistics.shield} · Armour {formatNumber(defence.statistics.armour)}</dd></div><div><dt>Field capacity</dt><dd>{defence.fieldState.used} of {defence.fieldState.capacity} used · Energy required {defence.energyRequired}</dd></div></dl><ul>{defence.requirements.map((requirement) => <li key={requirement.id}>{enumLabel(requirement.id)} level {requirement.requiredLevel}: {requirement.met ? 'met' : `current ${requirement.currentLevel}`}</li>)}</ul>{actionable ? <div className="stack"><label htmlFor={`quantity-${defence.id}`}>Quantity ({defence.quantity.min}–{defence.quantity.max})</label><div><button type="button" onClick={() => setQuantity(defence.id, quantity - 1)} disabled={quantity <= defence.quantity.min || busy !== null} aria-label={`Decrease ${defence.name} quantity`}>−</button><input id={`quantity-${defence.id}`} type="number" min={defence.quantity.min} max={defence.quantity.max} value={quantity} onChange={(event) => setQuantity(defence.id, Number(event.target.value))} disabled={busy !== null} /><button type="button" onClick={() => setQuantity(defence.id, quantity + 1)} disabled={quantity >= defence.quantity.max || busy !== null} aria-label={`Increase ${defence.name} quantity`}>+</button><button type="button" onClick={() => start(defence.id)} disabled={busy !== null}>{busy === defence.id ? 'Starting…' : `Build × ${quantity}`}</button></div></div> : <p role="status">{active ? 'Another Shipyard batch is in progress.' : defence.availability === 'COMING_LATER' ? 'Coming later — this defence cannot be started.' : !defence.meetsRequirements ? 'Requirements are not met.' : 'Insufficient authoritative resources.'}</p>}</article>; })}</div></section>
      {data.categories.map((category) => <section className="stack" id={`shipyard-${category.id}`} key={category.id}><h2>{category.name}</h2><div className="grid research-catalogue-grid">{data.catalog.filter((ship) => ship.category === category.id).map((ship) => { const quantity = quantities[ship.id] ?? 1; const actionable = ship.meetsRequirements && !active; return <article className="panel stack" key={ship.id}><div className="research-card-heading"><h3>{ship.name}</h3><span className="tag">Owned {formatNumber(ship.owned)}</span></div><p>{ship.description}</p><dl className="research-details"><div><dt>Cost</dt><dd>{formatNumber(ship.cost.alloy)} Alloy · {formatNumber(ship.cost.heliox)} Heliox · {formatNumber(ship.cost.aether)} Aether</dd></div><div><dt>Estimated duration</dt><dd>{Math.max(1, Math.round(ship.durationSeconds / 60))} minutes</dd></div><div><dt>Statistics</dt><dd>Speed {formatNumber(ship.statistics.speed)} · Cargo {formatNumber(ship.statistics.cargo)} · Fuel {ship.statistics.fuelPerDistance} · Attack {ship.statistics.attack} · Shield {ship.statistics.shield} · Armour {formatNumber(ship.statistics.armour)}</dd></div></dl><ul>{ship.requirements.map((requirement) => <li key={requirement.id}>{enumLabel(requirement.id)} level {requirement.requiredLevel}: {requirement.met ? 'met' : `current ${requirement.currentLevel}`}</li>)}</ul>{actionable ? <div className="stack"><label htmlFor={`quantity-${ship.id}`}>Quantity (1–100)</label><div><button type="button" onClick={() => setQuantity(ship.id, quantity - 1)} disabled={quantity <= 1 || busy !== null} aria-label={`Decrease ${ship.name} quantity`}>−</button><input id={`quantity-${ship.id}`} type="number" min="1" max="100" value={quantity} onChange={(event) => setQuantity(ship.id, Number(event.target.value))} disabled={busy !== null} /><button type="button" onClick={() => setQuantity(ship.id, quantity + 1)} disabled={quantity >= 100 || busy !== null} aria-label={`Increase ${ship.name} quantity`}>+</button><button type="button" onClick={() => start(ship.id)} disabled={busy !== null}>{busy === ship.id ? 'Starting…' : `Build × ${quantity}`}</button></div></div> : <p role="status">{active ? 'Another Shipyard batch is in progress.' : 'Requirements are not met.'}</p>}</article>; })}</div></section>)}
    </> : null}
  </section>;
}
